name: BugTemplate 
description: Formularz zgłoszenia defektu
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Wypełnij starannie wszystkie poniższe pola. Precyzyjnie opisany błąd pozwoli na szybsze rozwiązanie problemu.
  - type: dropdown
    id: priorytet
    attributes:
      label: Priorytet
      options:
        - Niski
        - Średni
        - Wysoki
        - Krytyczny
    validations:
      required: true      
  - type: dropdown
    id: System
    attributes:
      label: System
      description: Jakiego systemu dotyczy zgłoszenie?
      options:
        - Developerski
        - Testowy
        - PreProdukcji
        - Produkcja
    validations:
      required: true
  - type: input
    id: appTransaction
    attributes:
      label: Aplikacja/ Transakcja
      description: Wprowadź nazwe aplikacji lub transakcji
      placeholder: BP, FPP3
    validations:
      required: true
  - type: textarea
    id: issueRelation
    attributes:
      label: Powiązane Scenariusze testowe lub przypadki testowe
      description: Wprowadź numer powiązanych zgłoszeń rozpoczynając od znaku '#'
    validations:
      required: true
  - type: textarea
    id: descripiton
    attributes:
      label: Opis błędu
      description: Opisz na czym polega błąd.
      placeholder: 
      value: "np. Po uruchomieniu aplikacji ... i wypełnienieu pola ... nie ma walidacji wartości."
    validations:
      required: true
  - type: textarea
    id: asIs
    attributes:
      label: Stan aktualny
      description: Opisz jaki jest stan aktualny rozwiązania
  - type: textarea
    id: toBe
    attributes:
      label: Stan oczekiwany
      description: Opisz jaki jest stan oczekiwany rozwiązania
  - type: textarea
    id: kroki
    attributes:
      label: Kroki do wywołania błędu
      description: Opisz w jaki sposób ponowić błąd
      placeholder: 
      value: "1. Uruchom transkację ... 2. Wypełnij pole ... 3. Kliknij zapisz 4. Dane zapiszą się bez walidacji"
  - type: textarea
    id: dane
    attributes:
      label: Dane na jakich pojawił się błąd
      description: Podaj dane użyte, gdy pojawił się błąd
      
